[build-system]
requires = [
  "setuptools>=80.9.0",
  "wheel>=0.45.1"
]
build-backend = "setuptools.build_meta"

[project]
name = "CTC"
version = "4.0.0"

[tool.setuptools.packages.find]
where = ["lib"]

[project.scripts]
CTC = "CTC.cli:app"